spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bili?character-set=utf8mb4
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:com/example/bili/*.xml
  type-aliases-package: com.example.bili.entity
server:
  port: 8686